# Generated by Django 4.0.4 on 2022-05-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0002_alter_journal_publisher_alter_journal_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='num_pages',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='journal',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='journal',
            name='price',
            field=models.FloatField(),
        ),
    ]
